/**
 * Code implementations for Bubble Sort in multiple languages
 */

export const BUBBLE_SORT_PYTHON = [
  'def bubble_sort(arr):',
  '    n = len(arr)',
  '    ',
  '    # Traverse through all array elements',
  '    for i in range(n - 1):',
  '        swapped = False',
  '        ',
  '        # Last i elements are already in place',
  '        for j in range(0, n - i - 1):',
  '            # Traverse the array from 0 to n-i-1',
  '            # Swap if the element found is greater',
  '            # than the next element',
  '            if arr[j] > arr[j + 1]:',
  '                arr[j], arr[j + 1] = arr[j + 1], arr[j]',
  '                swapped = True',
  '        ',
  '        # If no swapping happened, array is sorted',
  '        if not swapped:',
  '            break',
  '    ',
  '    return arr'
];

export const BUBBLE_SORT_JAVA = [
  'public class BubbleSort {',
  '    public static void bubbleSort(int[] arr) {',
  '        int n = arr.length;',
  '        ',
  '        // Traverse through all array elements',
  '        for (int i = 0; i < n - 1; i++) {',
  '            boolean swapped = false;',
  '            ',
  '            // Last i elements are already in place',
  '            for (int j = 0; j < n - i - 1; j++) {',
  '                // Traverse the array from 0 to n-i-1',
  '                // Swap if the element found is greater',
  '                // than the next element',
  '                if (arr[j] > arr[j + 1]) {',
  '                    // Swap arr[j] and arr[j+1]',
  '                    int temp = arr[j];',
  '                    arr[j] = arr[j + 1];',
  '                    arr[j + 1] = temp;',
  '                    swapped = true;',
  '                }',
  '            }',
  '            ',
  '            // If no swapping happened, array is sorted',
  '            if (!swapped)',
  '                break;',
  '        }',
  '    }',
  '}'
];

export const QUICK_SORT_PYTHON = [
  'def quick_sort(arr, low, high):',
  '    if low < high:',
  '        # pi is partitioning index',
  '        pi = partition(arr, low, high)',
  '        ',
  '        # Separately sort elements before and after partition',
  '        quick_sort(arr, low, pi - 1)',
  '        quick_sort(arr, pi + 1, high)',
  '',
  'def partition(arr, low, high):',
  '    # Choose the rightmost element as pivot',
  '    pivot = arr[high]',
  '    ',
  '    # Pointer for greater element',
  '    i = low - 1',
  '    ',
  '    # Traverse through all elements',
  '    for j in range(low, high):',
  '        # If current element is smaller than or equal to pivot',
  '        if arr[j] <= pivot:',
  '            i = i + 1',
  '            # Swap elements',
  '            arr[i], arr[j] = arr[j], arr[i]',
  '    ',
  '    # Swap pivot element with element at i+1',
  '    arr[i + 1], arr[high] = arr[high], arr[i + 1]',
  '    return i + 1'
];

export const QUICK_SORT_JAVA = [
  'public class QuickSort {',
  '    public static void quickSort(int[] arr, int low, int high) {',
  '        if (low < high) {',
  '            // pi is partitioning index',
  '            int pi = partition(arr, low, high);',
  '            ',
  '            // Separately sort elements before and after partition',
  '            quickSort(arr, low, pi - 1);',
  '            quickSort(arr, pi + 1, high);',
  '        }',
  '    }',
  '    ',
  '    private static int partition(int[] arr, int low, int high) {',
  '        // Choose the rightmost element as pivot',
  '        int pivot = arr[high];',
  '        ',
  '        // Pointer for greater element',
  '        int i = (low - 1);',
  '        ',
  '        // Traverse through all elements',
  '        for (int j = low; j < high; j++) {',
  '            // If current element is smaller than or equal to pivot',
  '            if (arr[j] <= pivot) {',
  '                i++;',
  '                // Swap elements',
  '                int temp = arr[i];',
  '                arr[i] = arr[j];',
  '                arr[j] = temp;',
  '            }',
  '        }',
  '        ',
  '        // Swap pivot element with element at i+1',
  '        int temp = arr[i + 1];',
  '        arr[i + 1] = arr[high];',
  '        arr[high] = temp;',
  '        ',
  '        return i + 1;',
  '    }',
  '}'
];
