/**
 * Code implementations for sorting algorithms in multiple languages
 */

// ============= BUBBLE SORT =============
export const BUBBLE_SORT_PYTHON = [
  'def bubble_sort(arr):',
  '    n = len(arr)',
  '    ',
  '    for i in range(n - 1):',
  '        swapped = False',
  '        ',
  '        for j in range(0, n - i - 1):',
  '            if arr[j] > arr[j + 1]:',
  '                arr[j], arr[j + 1] = arr[j + 1], arr[j]',
  '                swapped = True',
  '        ',
  '        if not swapped:',
  '            break',
  '    ',
  '    return arr'
];

export const BUBBLE_SORT_JAVA = [
  'public class BubbleSort {',
  '    public static void bubbleSort(int[] arr) {',
  '        int n = arr.length;',
  '        ',
  '        for (int i = 0; i < n - 1; i++) {',
  '            boolean swapped = false;',
  '            ',
  '            for (int j = 0; j < n - i - 1; j++) {',
  '                if (arr[j] > arr[j + 1]) {',
  '                    int temp = arr[j];',
  '                    arr[j] = arr[j + 1];',
  '                    arr[j + 1] = temp;',
  '                    swapped = true;',
  '                }',
  '            }',
  '            ',
  '            if (!swapped) break;',
  '        }',
  '    }',
  '}'
];

// ============= SELECTION SORT =============
export const SELECTION_SORT_PYTHON = [
  'def selection_sort(arr):',
  '    n = len(arr)',
  '    ',
  '    for i in range(n - 1):',
  '        min_idx = i',
  '        ',
  '        for j in range(i + 1, n):',
  '            if arr[j] < arr[min_idx]:',
  '                min_idx = j',
  '        ',
  '        arr[i], arr[min_idx] = arr[min_idx], arr[i]',
  '    ',
  '    return arr'
];

export const SELECTION_SORT_JAVA = [
  'public class SelectionSort {',
  '    public static void selectionSort(int[] arr) {',
  '        int n = arr.length;',
  '        ',
  '        for (int i = 0; i < n - 1; i++) {',
  '            int minIdx = i;',
  '            ',
  '            for (int j = i + 1; j < n; j++) {',
  '                if (arr[j] < arr[minIdx]) {',
  '                    minIdx = j;',
  '                }',
  '            }',
  '            ',
  '            int temp = arr[i];',
  '            arr[i] = arr[minIdx];',
  '            arr[minIdx] = temp;',
  '        }',
  '    }',
  '}'
];

// ============= INSERTION SORT =============
export const INSERTION_SORT_PYTHON = [
  'def insertion_sort(arr):',
  '    for i in range(1, len(arr)):',
  '        key = arr[i]',
  '        j = i - 1',
  '        ',
  '        while j >= 0 and arr[j] > key:',
  '            arr[j + 1] = arr[j]',
  '            j -= 1',
  '        ',
  '        arr[j + 1] = key',
  '    ',
  '    return arr'
];

export const INSERTION_SORT_JAVA = [
  'public class InsertionSort {',
  '    public static void insertionSort(int[] arr) {',
  '        for (int i = 1; i < arr.length; i++) {',
  '            int key = arr[i];',
  '            int j = i - 1;',
  '            ',
  '            while (j >= 0 && arr[j] > key) {',
  '                arr[j + 1] = arr[j];',
  '                j--;',
  '            }',
  '            ',
  '            arr[j + 1] = key;',
  '        }',
  '    }',
  '}'
];

// ============= QUICK SORT =============
export const QUICK_SORT_PYTHON = [
  'def quick_sort(arr, low, high):',
  '    if low < high:',
  '        pi = partition(arr, low, high)',
  '        quick_sort(arr, low, pi - 1)',
  '        quick_sort(arr, pi + 1, high)',
  '',
  'def partition(arr, low, high):',
  '    pivot = arr[high]',
  '    i = low - 1',
  '    ',
  '    for j in range(low, high):',
  '        if arr[j] <= pivot:',
  '            i += 1',
  '            arr[i], arr[j] = arr[j], arr[i]',
  '    ',
  '    arr[i + 1], arr[high] = arr[high], arr[i + 1]',
  '    return i + 1'
];

export const QUICK_SORT_JAVA = [
  'public class QuickSort {',
  '    public static void quickSort(int[] arr, int low, int high) {',
  '        if (low < high) {',
  '            int pi = partition(arr, low, high);',
  '            quickSort(arr, low, pi - 1);',
  '            quickSort(arr, pi + 1, high);',
  '        }',
  '    }',
  '    ',
  '    private static int partition(int[] arr, int low, int high) {',
  '        int pivot = arr[high];',
  '        int i = low - 1;',
  '        ',
  '        for (int j = low; j < high; j++) {',
  '            if (arr[j] <= pivot) {',
  '                i++;',
  '                int temp = arr[i];',
  '                arr[i] = arr[j];',
  '                arr[j] = temp;',
  '            }',
  '        }',
  '        ',
  '        int temp = arr[i + 1];',
  '        arr[i + 1] = arr[high];',
  '        arr[high] = temp;',
  '        return i + 1;',
  '    }',
  '}'
];

// ============= MERGE SORT =============
export const MERGE_SORT_PYTHON = [
  'def merge_sort(arr):',
  '    if len(arr) > 1:',
  '        mid = len(arr) // 2',
  '        left = arr[:mid]',
  '        right = arr[mid:]',
  '        ',
  '        merge_sort(left)',
  '        merge_sort(right)',
  '        ',
  '        i = j = k = 0',
  '        ',
  '        while i < len(left) and j < len(right):',
  '            if left[i] <= right[j]:',
  '                arr[k] = left[i]',
  '                i += 1',
  '            else:',
  '                arr[k] = right[j]',
  '                j += 1',
  '            k += 1',
  '        ',
  '        while i < len(left):',
  '            arr[k] = left[i]',
  '            i += 1',
  '            k += 1',
  '        ',
  '        while j < len(right):',
  '            arr[k] = right[j]',
  '            j += 1',
  '            k += 1',
  '    ',
  '    return arr'
];

export const MERGE_SORT_JAVA = [
  'public class MergeSort {',
  '    public static void mergeSort(int[] arr, int left, int right) {',
  '        if (left < right) {',
  '            int mid = (left + right) / 2;',
  '            ',
  '            mergeSort(arr, left, mid);',
  '            mergeSort(arr, mid + 1, right);',
  '            merge(arr, left, mid, right);',
  '        }',
  '    }',
  '    ',
  '    private static void merge(int[] arr, int left, int mid, int right) {',
  '        int n1 = mid - left + 1;',
  '        int n2 = right - mid;',
  '        ',
  '        int[] L = new int[n1];',
  '        int[] R = new int[n2];',
  '        ',
  '        for (int i = 0; i < n1; i++)',
  '            L[i] = arr[left + i];',
  '        for (int j = 0; j < n2; j++)',
  '            R[j] = arr[mid + 1 + j];',
  '        ',
  '        int i = 0, j = 0, k = left;',
  '        ',
  '        while (i < n1 && j < n2) {',
  '            if (L[i] <= R[j]) {',
  '                arr[k] = L[i];',
  '                i++;',
  '            } else {',
  '                arr[k] = R[j];',
  '                j++;',
  '            }',
  '            k++;',
  '        }',
  '        ',
  '        while (i < n1) {',
  '            arr[k] = L[i];',
  '            i++;',
  '            k++;',
  '        }',
  '        ',
  '        while (j < n2) {',
  '            arr[k] = R[j];',
  '            j++;',
  '            k++;',
  '        }',
  '    }',
  '}'
];

// ============= HEAP SORT =============
export const HEAP_SORT_PYTHON = [
  'def heap_sort(arr):',
  '    n = len(arr)',
  '    ',
  '    # Build max heap',
  '    for i in range(n // 2 - 1, -1, -1):',
  '        heapify(arr, n, i)',
  '    ',
  '    # Extract elements one by one',
  '    for i in range(n - 1, 0, -1):',
  '        arr[0], arr[i] = arr[i], arr[0]',
  '        heapify(arr, i, 0)',
  '    ',
  '    return arr',
  '',
  'def heapify(arr, n, i):',
  '    largest = i',
  '    left = 2 * i + 1',
  '    right = 2 * i + 2',
  '    ',
  '    if left < n and arr[left] > arr[largest]:',
  '        largest = left',
  '    ',
  '    if right < n and arr[right] > arr[largest]:',
  '        largest = right',
  '    ',
  '    if largest != i:',
  '        arr[i], arr[largest] = arr[largest], arr[i]',
  '        heapify(arr, n, largest)'
];

export const HEAP_SORT_JAVA = [
  'public class HeapSort {',
  '    public static void heapSort(int[] arr) {',
  '        int n = arr.length;',
  '        ',
  '        // Build max heap',
  '        for (int i = n / 2 - 1; i >= 0; i--)',
  '            heapify(arr, n, i);',
  '        ',
  '        // Extract elements one by one',
  '        for (int i = n - 1; i > 0; i--) {',
  '            int temp = arr[0];',
  '            arr[0] = arr[i];',
  '            arr[i] = temp;',
  '            ',
  '            heapify(arr, i, 0);',
  '        }',
  '    }',
  '    ',
  '    private static void heapify(int[] arr, int n, int i) {',
  '        int largest = i;',
  '        int left = 2 * i + 1;',
  '        int right = 2 * i + 2;',
  '        ',
  '        if (left < n && arr[left] > arr[largest])',
  '            largest = left;',
  '        ',
  '        if (right < n && arr[right] > arr[largest])',
  '            largest = right;',
  '        ',
  '        if (largest != i) {',
  '            int temp = arr[i];',
  '            arr[i] = arr[largest];',
  '            arr[largest] = temp;',
  '            ',
  '            heapify(arr, n, largest);',
  '        }',
  '    }',
  '}'
];
